### ISSUE TITLE
ARPACK Solver does not exit!

### ISSUE THREAD

**Issue by ajos6183** [wo80/csparse-interop#5]
Hello @wo80,

I am running into some cases where the ARPACK solver does not exit and keeps running with no CPU usage. I have included an example below with [these matrices](https://github.com/wo80/csparse-interop/files/2477392/Matrices.zip) (thanks for including the new matrix writer!).

The way i can get this particular example to work is if i change the requested number of eigenvalues to something other than k =12. One way to get it to work is to throw an exception that way a catch statement can be used and the parameter k changed. What are your thoughts?

    Dim kg = CSparse.IO.MatrixMarketReader.ReadMatrix(Of Double)("C:\Users\Anthony\Desktop\Kg")
    Dim ke = CSparse.IO.MatrixMarketReader.ReadMatrix(Of Double)("C:\Users\Anthony\Desktop\Ke")
    Dim Eig As CSparse.Double.Solver.Arpack = New CSparse.Double.Solver.Arpack(kg.ToSparseMatrix, ke.ToSparseMatrix) With {.Tolerance = 10 ^ -5, .ComputeEigenVectors = True, .Iterations = 1000}
    Dim Solution As CSparse.Interop.ARPACK.ArpackResult(Of Double) = Eig.SolveGeneralized(12, CSparse.Interop.ARPACK.Job.LargestMagnitude)

Regards,
Anthony

**Comment by wo80** [comment]
Your matrix has the following upper spectrum:

		[0]  (-0,00780664290681401, 0)
		[1]  (-0,00188223622729905, 0)
		[2]  (-0,000871520548740089, 0)
		[3]  (-0,000759868809238474, 0)
		[4]  (-0,000618146568597974, 0)
		[5]  (-0,000512589555268826, 0)
		[6]  (-0,000419262333542144, 0)
		[7]  (-0,000410351215346901, 0)
		[8]  (-0,000316441854258941, 0)
		[9]  (-0,000232139455824873, 0)
		[10] (-0,000221791544774624, 0)}
		[11] (-0,000220872821872396,  4,56419592711548E-06)
		[12] (-0,000220872821872396, -4,56419592711548E-06)
		[13] (-0,000175358228833433, 0)
		[14] (-0,000177263647559269, 0)

Now, when requesting `nev = 12` eigenvalues, the pair of conjugate eigenvalues would be split. Instead ARPACK computes both eigenvalues, which leads to a total number of 13 converged eigenvalues. This leads to memory corruption, since the size of eigenvalue storage is `nev` and the size of eigenvector storage is `nev * n`, so at some point ARPACK will access memory that should not be accessed.

The solution is to always allocate memory for `nev + 1` eigenvalues when dealing with real non-symmetric problems.

**Comment by ajos6183** [comment]
Thanks for the quick resolution!
